github: [Aditya060806]
ko_fi: aditya060806
custom: ["https://www.blockchain.com/explorer/addresses/btc/YOUR_BTC_ADDRESS_HERE", "https://www.blockchain.com/explorer/addresses/eth/YOUR_ETH_ADDRESS_HERE"]
